### PR TITLE
MEL-893 ConstraintViolationException in faas-agent

### PR DESCRIPTION
**Pull request by pszkup7bulls**

### CODE REVIEW

**Review by dbaur — CHANGES_REQUESTED** [review]
Not sure if this helps for several reasons:
 a) there may be multiple instances of this class, so synchronizing on one instance is not enough.
 b) when reaching this point, both threads are already within a transaction, so even if one thread writes the tenant, the other thread will not see it

**Comment by pszkup7bulls** [comment]
> Not sure if this helps for several reasons:
> a) there may be multiple instances of this class, so synchronizing on one instance is not enough.
> b) when reaching this point, both threads are already within a transaction, so even if one thread writes the tenant, the other thread will not see it

Ok, so what is your recommendation? How to solve this issue: https://jira.7bulls.eu/browse/MEL-893 ?

**Comment by dbaur** [comment]
Please synchronize on class not on instance, or inject it in singleton scope, otherwise this will not have any effect.

**Comment by pszkup7bulls** [comment]
> Please synchronize on class not on instance, or inject it in singleton scope, otherwise this will not have any effect.

Thank you for your response. I am not the Guice expert so I did not know that bindind does not create singletons.
I have added @Singleton annotation on helper classes.

**Review by dbaur — APPROVED** [review]

**Pull request merged**
